#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href /ecalc/

after_script:
  - bash ./deploy-gp.sh

env:
  global:
  - GH_REF: github.com/imperger/ecalc.git